{
    parserClass='run.gleam.lang.core.parser.GleamParser'
    parserUtilClass='run.gleam.lang.core.parser.GleamParserUtil'

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="Gleam"
    psiImplClassSuffix="Impl"
    psiPackage="run.gleam.lang.core.psi"
    psiImplPackage="run.gleam.lang.core.psi.impl"

    elementTypeHolderClass="run.gleam.lang.core.psi.GleamTypes"
    elementTypeClass="run.gleam.lang.core.psi.GleamElementType"
    tokenTypeClass="run.gleam.lang.core.psi.GleamTokenType"

    tokens = [
        // Keywords
        PUB = "pub"
        FN = "fn"
        LET = "fet"
        CASE = "case"
        IMPORT = "import"
        TYPE = "type"
        ASSERT = "assert"
        TODO = "todo"
        CONST = "const"
        EXTERNAL = "external"

        // Regexp
        IDENTIFIER = "regexp:[_a-z][_0-9a-z]*"
        COMMENT = "regexp://[^\n]*"
        TYPE_IDENTIFIER = "regexp:[A-Z][_0-9a-zA-Z]*"

        // Chars
        LBRACE      =  '{'
        RBRACE      =  '}'
        LBRACK      =  '['
        RBRACK      =  ']'
        LPAREN      =  '('
        RPAREN      =  ')'

        COLON       =  ':'

        COMMA       =  ','

        EQ          =  '='
        EQEQ        =  '=='

        BANG        =  '!'

        PLUS        =  '+'
        MINUS       =  '-'

        OR          =  '||'
        AND         =  '&&'

        LT          =  '<'
        GT          =  '>'

        MUL         =  '*'
        DIV         =  '/'
        DIVDIV      =  '//'

        DOT         =  '.'
        DOTDOT      =  '..'

        FAT_ARROW   =  '=>'
        ARROW       =  '->'

        QUOTE       =  '"'
    ]
}

gleamFile ::= topLevelDefinition*
private topLevelDefinition ::=
    importStatement
    | typeStatement
    | functionStatement
    | COMMENT

private innerDefinition ::=
    COMMENT

private constructorElement ::= constructorIdentifier TYPE_IDENTIFIER [COMMA]
constructorIdentifier ::= IDENTIFIER COLON

importStatement ::= IMPORT importStatementElement
importStatementElement ::= IDENTIFIER ('/' IDENTIFIER [importStatementTypes])*
importStatementTypes ::= DOT LBRACE ((TYPE_IDENTIFIER|IDENTIFIER) [COMMA])* RBRACE

// TODO improve type statement parsing
typeStatement ::= [PUB] TYPE TYPE_IDENTIFIER LBRACE (typeStatementConstructor)* RBRACE
typeStatementConstructor ::= TYPE_IDENTIFIER LPAREN (constructorElement)* RPAREN

functionStatement ::= [PUB] FN IDENTIFIER LPAREN [(constructorElement)*] RPAREN [functionStatementType] LBRACE [innerDefinition*] RBRACE
functionStatementType ::= ARROW TYPE_IDENTIFIER