{
    parserClass='run.gleam.lang.core.parser.GleamParser'
    parserUtilClass='run.gleam.lang.core.parser.GleamParserUtil'

    extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

    psiClassPrefix="Gleam"
    psiImplClassSuffix="Impl"
    psiPackage="run.gleam.lang.core.psi"
    psiImplPackage="run.gleam.lang.core.psi.impl"

    elementTypeHolderClass="run.gleam.lang.core.psi.GleamTypes"
    elementTypeClass="run.gleam.lang.core.psi.GleamElementType"
    tokenTypeClass="run.gleam.lang.core.psi.GleamTokenType"

    tokens = [
        LBRACE      =  '{'
        RBRACE      =  '}'
        LBRACK      =  '['
        RBRACK      =  ']'
        LPAREN      =  '('
        RPAREN      =  ')'
        COLON       =  ':'
        SEMICOLON   =  ';'
        COMMA       =  ','
        EQ          =  '='
        BANGEQ      =  '!='
        EQEQ        =  '=='
        BANG        =  '!'
        PLUSEQ      =  '+='
        PLUS        =  '+'
        MINUSEQ     =  '-='
        MINUS       =  '-'
        OR          =  '||'
        LT          =  '<'
        MUL         =  '*'
        DIV         =  '/'
        DIVDIV      =  '//'
        GT          =  '>'
        DOTDOT      =  '..'
        FAT_ARROW   =  '=>'
        ARROW       =  '->'
        Q           =  '?'
    ]
}

gleamFile ::= statement*

statement ::= import | comment

import ::= "import"
comment ::= DIVDIV (ALPHA | WSP)*